# Generated by Django 5.0.6 on 2024-07-14 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='time',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
